version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    container_name: VehicleWiki
    environment:
      POSTGRES_DB: VehicleWiki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
